runtime: nodejs10
# Update with Redis instance details
env_variables:
  REDISHOST: '10.176.0.3'
  REDISPORT: '6379'
# Update with Serverless VPC Access connector details
vpc_access_connector:
  name: 'projects/barkey/locations/us-central1/connectors/app-engine-conn'
